version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set the backend API base URL that the frontend will use at build time
        # Example: http://backend.yourdomain.com/api or http://backend:8080/api
        VITE_API_BASE: ${VITE_API_BASE:-/api}
    image: frooooooont:latest
    container_name: frooooooont
    ports:
      - "${PORT:-8080}:80"
    restart: unless-stopped
