services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set the backend API base URL that the frontend will use at build time
        # Example: http://backend.yourdomain.com/api or http://backend:8080/api
        VITE_API_BASE: ${VITE_API_BASE:-/api}
    image: spay-frontend:latest
    container_name: spay-frontend
    ports:
      # Default host port changed to 8081 to avoid conflicts; override with PORT env or remove this block if using an external proxy
      - "${PORT:-80}:80"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"